config/routes.rb
Rails.application.routes.draw do
  get 'encounters/blacksmith'
  get 'encounters/rummage'
  get 'encounters/monster'
  get 'heros/home'
  get 'items/:id/upgrade', to: 'items#upgrade'
  resources :items
  resources :monsters
  resources :heros
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hero.rb
class Hero < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :hero

    def upg_exp_cost
        1.5 * self.bonus
    end 
    
    def upg_amt
        0.1 * self.bonus 
    end 

    def stat_name 
        case self.stat 
        when "attk_val" 
            "attack value"
        when "def_val"
            "defense value"
        when "hp"
            "hit points"
        else 
            "You broke something"
        end
    end
end

app/models/monster.rb
class Monster < ApplicationRecord
    def randomize
        self.hp = rand((0.8 * Hero.find(1).hp)..(1.2 * Hero.find(1).hp))
        self.attk_val = rand((0.8 * Hero.find(1).attk_val)..(1.2 * Hero.find(1).attk_val))
        self.def_val = rand((0.8 * Hero.find(1).def_val)..(1.2 * Hero.find(1).def_val))
        self.exp_gain = self.hp * 0.2
        self.save 
    end 

    def stat_name 
        case self 
        when "attk_val"
            "attack strength"
        when "def_val" 
            "defense strength"
        when "hp"
            "hit points"
        when "exp_gain"
            "experience point yield"
        else 
            "You broke something"
        end 
    end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_hero
    def current_hero  
        current_hero = Hero.find(1)  
    end 
end

app/controllers/encounters_controller.rb
class EncountersController < ApplicationController
  def blacksmith
    @hero = current_hero 
  end

  def rummage
  end

  def monster
  end
end

app/controllers/heros_controller.rb
class HerosController < ApplicationController
    def new 
        @hero = Hero.new 
    end 

    def create 
        @hero = Hero.create(hero_params)
        if @hero.save
            redirect_to hero_path(@hero) 
        else 
            render 'new'
        end 
    end 

    def show 
        @hero = Hero.find_by(params[:id])
    end 

    private 

    def hero_params
        params.require(:hero).permit(:name, :attk_val, :def_val, :hp, :exp_total)
    end 
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

    def upgrade
        @item = Item.find_by(params[:id])
        @hero = Hero.current_hero
        if @hero.exp_total < @item.upg_exp_cost
            redirect_to "/encounters/blacksmith", notice: "You don't have enough exp to do this."
        elsif @hero.exp_total >= @item.upg_exp_cost
            render 'upgrade' 
        end
    end 

    def show 
        @item = Item.find_by(params[:id])
    end

end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController

    def new 
        @monster = Monster.new 
    end 

    def create
        @monster = Monster.create
        @monster.randomize 
        redirect_to @monster
   end 

    def show 
        @monster = Monster.find(params[:id])
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/encounters_helper.rb
module EncountersHelper
    def blacksmith
        @hero = Hero.find(1)
    end 
end

app/helpers/heros_helper.rb
module HerosHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/views/encounters/blacksmith.html.erb
<title>Blacksmith</title>
<p></p>
<% flash.each do |type, msg| %>
    <div class="flash">
      <%= msg %>
    </div>
  <% end %>
<h1>The grizzled blacksmith welcomes you into his workshop... </h1>

<h3> You have <%= @hero.exp_total %> Experience Points that you can spend! </h3>

<h3> Which item would you like to upgrade? </h3>
<ol>
<% @hero.items.each do |item| %>
    <li><%= link_to item.name, "/items/#{item.id}/upgrade" %></li> 
    <% end %>
    </ol>

app/views/encounters/monster.html.erb
<h2>A shadowy beast approaches... </h2>
<%= link_to "FIGHT!", new_monster_path %>

app/views/encounters/rummage.html.erb
<h1>Encounters#rummage</h1>
<p>Find me in app/views/encounters/rummage.html.erb</p>

app/views/heros/_form.html.erb
<%= form_for hero do |f| %>
    <% if hero.errors.any? %>
    <ul>
      <% hero.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <% end %>
    <p>Name Your Hero!</p>
    <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </p>
    <%= f.hidden_field :attk_val, value: 10 %>
    <%= f.hidden_field :hp, value: 15 %>
    <%= f.hidden_field :def_val, value: 10 %>
    <%= f.hidden_field :exp_total, value: 0 %>
    <%= f.submit %>
    <% end %>

app/views/heros/home.html.erb
<h1> How Would You Like To Continue Your Journey? </h1>

<h3> <%= link_to "Go to the Blacksmith", "/encounters/blacksmith" %> </h3>

<h3> <%= link_to "Fight a Monster", "/encounters/monster" %> </h3>

<h3> Rummage for Items </h3>

app/views/heros/new.html.erb
<%= render partial: 'form', locals: { hero: @hero} %>

app/views/heros/show.html.erb
<h1> Your Hero! </h1>
<h3> Name: <%= @hero.name %></h3>

<div> HP: <%= @hero.hp %> </div>
<div> Attack Power: <%= @hero.attk_val %> </div>
<div> Defense Power: <%= @hero.def_val %> </div>
<div> Experience Points: <%= @hero.exp_total %> </div>

<%= link_to "Embark on Your Adventure!", "home" %>

app/views/items/_item.html.erb
<h1> <%= item.name %> </h1>

<div> This item boosts your <%= item.stat_name %> by <%= item.bonus %> points! </div>

app/views/items/show.html.erb
<%= render partial: 'item', locals: { item: @item} %>

app/views/items/upgrade.html.erb
<h1>Upgrade Your Item Here</h1>

<h3> You have <%= Hero.find(1).exp_total %> experience points to spend. </h3>

<h3><%= @item.name %> will cost <%= @item.upg_exp_cost.to_i %> exp points to upgrade. 
Upgrading it will increase its bonus to your <%= @item.stat_name %> by <%= @item.upg_amt %> 
to a total of <%= @item.bonus + @item.upg_amt %></h3>
<h3> Would you like to upgrade it? </h3>
<%= button_to 'Yes', item_path(@item), :method => :get %>
<%= button_to 'No', "/encounters/blacksmith", :method => :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LegacyGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= link_to "My Hero", hero_path(Hero.find(1)) %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/monsters/new.html.erb
<%= button_to "Find a monster!", monsters_path %>

app/views/monsters/show.html.erb
<h1>FIGHT MONSTER NUMBER <%= @monster.id %></h1>

<ul>
<% @monster.attributes.each do |key, value| %>
    <ul>
<li><%= key %>: <%= value %></li>
</ul>
<% end %>
</ul>